version: "3"
services:
  #Laravel Application
  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: espn-app
    container_name: espn-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
        - APP_ENV=local
        - APP_KEY=base64:OFFt9LUfICGigLqXzcx6xKP1iVY+e0U9Pm9NRyey+Go=
        - APP_DEBUG=true
        - APP_URL=http://localhost
        - DB_CONNECTION=mysql
        - DB_HOST=db
        - DB_PORT=3306
        - DB_DATABASE=test
        - DB_USERNAME=root
        - DB_PASSWORD=test321
    working_dir: /var/www
    ports:
      - "3001:3000"
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - espn-network


  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - "4307:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: test321
      MYSQL_ROOT_PASSWORD: test321
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/dbdata:/var/lib/mysql/
    networks:
      - espn-network


#Docker Networks
networks:
  espn-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
